name: Automated API tests using Postman CLI

on: push

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key PMAK-65182d7bb1a7a4003e31bd1b-b8fc6ff738c02145aef3bd8d85cae218e5
      - name: Run API tests
        run: |
          postman collection run "${{ github.workspace }}/postman/collections/✅ Assignment #5.json" -e "25457889-4351ccfb-d3c0-41f1-bc42-72d63bd7816e"  
